language: node_js
node_js:
- '4.2'

env:
  global:
  - secure: Av8WGR9fT7QGBui4qsXAtuDDV9vr64YGfic8xX/bi9QZR30V/lp+D82yGjIosYbHv6dTW0OQM15UcIPOxhTYpDx/9VjAFp6ajQy7zBUv74Eq7PVnWZGqQD/ebpeBignqovrkNqwK9MPlcieXGLnBeRY91Kj6X0A0iDgOQ6U61hWaznPl7uI6+tp5PbvsGdzvmFI22oEg6IyQ4ToSiisVpf0dNk4qzDDRCROMP+VuQyNfmvvj+Ycza+YUgtJGnktBIJIHNcH+kETJMjiINQdxW0JMsVwwxfxuoynBtlYLrKMw3I5CfyCW2CY4ezTCDirwpGsLvpo5tmQWuI2NuKz3w8PSYh1JTgIJhp/nc56dlqGjog74edeSuXncfjDJ+WEjAvouiNIdUlIYy63SzXI4zS977Rg03KJYHIwdRHD7gYe9VL6qcKL34En2krLIqKMkLqu5/i+BkkWohz8M+RNvGxDKD5b4ZHp651/Q8XJJANC6Ivg2W58qnY1grr3TMj6EDi4DzAr0H2oAyLUYmJlHZcEuUBAEbzY6qmvKEb2IJGtdAJeoybVXpy+SSLbxvMNFx3zNxo24h/2iIG/cDb1n0J+q3XDUCVyVfISbOgv3umefieOr3w3iizerKu5SQnid7v8bMV1gA7oJDBJUYtnCRsMhawu969kNXwWuofrA1YM=
  - secure: b3IEmMfwFI6Tya56SNyrItSwK/VMq0NKtfjQ4bvoGvsiyHbm4v91DUJuKh8Xgzdxd9nHA8STNJwILePPVKDyKVgFFgOEPlRpYR5Lb809FxTZDHo5L5Do0VMRx6yIcfSrxlpyErpyojUxbcHs4fYk8fL/TtW3r3pkD2Ws0xcyVHcxEt4dgCExaw72b3byjAgWsMbkw0towb9pvR30MPlCRjH1zZCP0N1/Jfq+F7VUisSx1r1hnH2+JCFGLHX+zLXjg6MJeDXw4J9oDD0RS4xWafRDsLYPDIip0ZSbwL8HF6qqaJYBiClfQxfYLdEnexvQmYRVfRrCjMVlcO319mchpG0GtNSqGAbGiiQ70e9BRDuN1Rpzkn4naHtFGF1Gjc2YaG+xntW4ewXxcnLtxrYdZBccBs+umn3N3oyI2BSpsOMA0rDmNgjl1n4g9CkbvlgGde4Yp8nGSpUGgQ1DroOMdiCsUmGWjVNLP8fSjMwxFeKi9hqV5FzgQC+zpnsSIc3dco+vl34pNOkfeigsaIN8jcAMhFN8yV2kvEieWv8eSzOoAc2rg8leavSdk9CRsLft6w1CSamgvpFgAYlvCnqxYGanB+sAdWWdTfLmyJJvrTcxfvC7X9gXrFPwQ2MhWC633XTD9najqjida5T+heFSCBA3xmk7FfyisH41BXRL6Z4=
  - secure: n8pJQcmHDmQ73LhVVcWIkzCVAAioIdO4btBLrxeH2B7qb6c0ZO46pfL0JRmKwo5IjZhIxzYQ1Fg56ngxKWHc/m276+Fx/HuupxoNlHfeacOKraHV5772QbelubDORk+skxKyLxbfwPNiyF6HxHg+/HT6b8wBqP258i1/u38uI9xm7mYGWfZL9c03lEyClRvH+3EnXq/ASqz+dJ1KaGS72DvRLNBVXheGBkz1tWtBtGmX+2u/6MUvW3+djONhD0jYb3Okao+1gUiPRneL6F2P5YA0IA5KL4XUi6vyJhSnXS52BVbGIb06a7jS4T0QVxP8yYefwhKOtPaASewalO5+MlXzKr7QeFRmRVhGYuSq8BUEK2usaJUBsV+m7bY7bw3O9aBwogszqSLmVSe6RR7oK5NlJcCFsZOuS/eXgpC3xW8AoSQxh7TnR76cOZ936bYdHwzqRYSOoq/dnHq2psjLznuiJI3Xog9qutTP2E/ULLzaIwt7D6QGVwT55oO56BTkXCiszPsSOLT2DsypUGraPBcLvUeqg29WFf9gizsCjXoNyBDVjgJ3IeKTb8ePg77z42XPvV4ouuXyiFNDmOwmr2/eIZDc0hlIN2Kfo/VNcXk5bNO/Zn1A+N1ME64+NgfQEiRGjIlv5TaWspOwFnGgVpYlRhVh6LjrBmWcHf6S2KE=

script:
- echo 'No test'

before_deploy:
- sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    tags: true
