language: node_js
node_js:
  - '4.2'

env:
  global:
  - secure: cJEIJxiOdO8OOYp/Gcb4MK0CBL8fpG1J1BaD6JMLGr+d4YpHqxMvRPC/EhGnQWZTl3oXAOt6XAUjHF2V+l+1eTgNsKdonL1MYFIaAYA2zxK63T1vD18uMsrAJJAEwOkb4ZrUQUp/ELY+stDkyq+bnPwlQ5s+WHrxSUqpBZFNvF+yvB22+qb3grpeHdrcQlcbT1oJbA1QaOSbxow5qxkVXcgLwrwOXFs3vpwsUzsy6yAzCAp6qIM0A6m6JTMzGHS9VKwEU6HqH9CcSK8vYPEAhxHz+hcIvj6MuAc4d9nilQrZPV6AdyVtz6aGDph9TPQzTy0Trh9FEe8p3d0LIJ480hUztDVmXlrEz46WimH5ucYANtnZusPrHP8/R+rI47Jg9YFVcXicXG4One1/eoHDwxxMfpqFzsHbdlDj+jxinm4xSkM3+OXron1xQ4F+yeXi9yESlq4iwPjVKQLKRGmCjZDwrsHk06U9kJHXKjCBhYAHECb3kTHIRH1qbsx4sCqaFUNLvtWmzXAOfsJEoOMuEqkBVCtjU6JHD+6yfVpfIrA3fawJztPHjpraUGpWqz0B+eyrViF2+N5899OaSOxefp2fbLShljUESZonjCdedl1BB62LginkxO9qkpTclibYrAoNHP3o4uHg9q/fkpctqf5QMJ9RYDvGMdKc1lGAGAE=
  - secure: g46aymDP3alLL2Ra49GhXU9jI8fltvqvAs76jvpzBdkh0r04F6EQApyXJqGrWg1S2vTyh/wFu57ZCZOdODUA/t52mHmYcjYSXGKf6E015C7ENc1PCmzC0LIy0cAP9oowCPNJlLW25Kelkc5mCxyiob3UPCI69fUvMONcx0TzQchdbkPxsHVPgEfy2RB50tqXF1m1y4LC6TAi0Hd11K+vA0IizJzZXArVfJXSZq59YMdNQKF+dbYqonfrIltjOTH1hq0iQlK/356syaSQ2A6L1K3zODF9tR+rSWfPjhI/aJDGa1Wi6NjA+np27u8e5HKG4B2vezIxgD9EIoJqD5+I2jTZwTqAFb3i4JkU5i432a9sYODhGQdntIjcoSXAqFnc6jUJyHqhu8pms8mjwHwLtUHH6yG/D/DYsPB8YEYf4Hic/hTDsV7kpyxh68hDGVNVNoEVbOHNifg/nP11Io3yTmSyAtIsBBdAWkwGL78VUZmBIWsYiP1jOOLoOSXntr4RKFIKrkhJLqW/c8TQNfhmRlmR8kgrYHAOSiuZ4ULsRZji8S8nb0INB1f4TqkGwNhQLpbRwWLNlbFXUFz2lrdv1/jaExWuoJ3IArdrftCTvg6H4He0DxZNqt09KNP2cSHccx5YknXypQ5rS6k8vL34eSafTmsxHsRWOO/GcNoqUpk=
  - secure: uEN1TK5wqEsVqvMgsKtM7jGeNh6/bpFXk18Ht+w0uAozC2qkVSF28B5YpGCq5DVuvSC525AMrmuuYo4DHaBKEC4MGEzE/R0jLrHY2930zKLYwK+OPHD9BnTWd2cq4Gxk2eNcmmb8prRoyCA1XQ/jLdlfPKos/kM6loEzy4mFaOPNHGF/gx/7NugUFKMn1v8pg4Fgo14FqbehA+QO62GwYKXRgjT1uPnc9FCmW2jKkhvjrRMVr7NGokRNsxldyefGJpG78dGtJKlhHIMhztrlCqQFRg2anK4dXhK1dMCR7CQFwg/D1zU6DlavVU8WibxW4zToxkWibvZs5lOxeiqhTHhmC9jxIPmDnK3xYXoTI9OqAqHcmQcwLCMT+BUFNr2IYsqCAt1T264aMi3yMou1InG5Pm6ZBLmvgkYNbIsJoYCv+y5c/cDL4E8j7jOZF4xCUnrXQ2c5Zb0Smh+nEuo0UJUOQqV9AD1eoctH8dBc+h9mY2sx5A19sNtHds2sYfeuTodvBeGjgn6rd7cI+pyslsTLkOIqk75HPesrn9oov6/8eIueIEfTkj6ufP2E6g6U7lBuW4mVeXIr2VimeLmbJYZAfXkasNq3AShIZEX65Q7yXjxXV0K5Jx/TXJh3SS555P/HFv/mv18R1lVJu5kF7joWIi6/bC+i1wwqG8RWz1Y=

script:
  - echo 'No test'

before_deploy:
  - sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    tags: true
