AWSTemplateFormatVersion: 2010-09-09
Description: |
  Chatanoo Infrastructure

# Metadata:

Parameters:
  DomainName:
    Type: String
  ProjectName:
    Type: String

  DeploymentUrl:
    Type: String
    Default: https://s3-eu-west-1.amazonaws.com/chatanoo-deployment/
  DeploymentBucket:
    Type: String
    Default: chatanoo-deployment

# Mappings:

# Conditions:

Resources:

  Repo:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Retain"
    Properties:
      Tags:
        - Key: 'chatanoo:project'
          Value: !Ref ProjectName

  LambdaCustomResources:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join ['', [!Ref DeploymentUrl, 'infra/resources/1.0.6.cform']]
      Parameters:
        DeploymentBucket: !Ref DeploymentBucket
        CloudFrontIdentityKey: "aws-cloudformation-cloudfront-identity/1.0.1.zip"
        CognitoIdentityPoolKey: "aws-cloudformation-cognito-identitypool/1.0.0.zip"
        CognitoIdentityPoolRolesKey: "aws-cloudformation-cognito-identitypoolroles/1.0.0.zip"
        CognitoUserPoolKey: "aws-cloudformation-cognito-userpool/1.0.0.zip"
        CognitoUserPoolClientKey: "aws-cloudformation-cognito-userpoolclient/1.0.1.zip"
        CognitoUserPoolCustomAttributesKey: "aws-cloudformation-cognito-userpoolcustomattributes/1.0.1.zip"
        DynamoDBItemKey: "aws-cloudformation-dynamodb-item/1.0.0.zip"
        ElasticTranscoderPipelineKey: "aws-cloudformation-elastic-transcoder-pipeline/1.0.0.zip"
        ElasticTranscoderPresetKey: "aws-cloudformation-elastic-transcoder-preset/1.0.0.zip"
        S3UploaderKey: "aws-cloudformation-s3-uploader/1.0.0.zip"
      Tags:
        - Key: 'chatanoo:project'
          Value: !Ref ProjectName
        - Key: 'chatanoo:component'
          Value: 'resources'

  Network:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join ['', [!Ref DeploymentUrl, 'infra/network/1.0.0.cfn.yml']]
      Parameters:
        ProjectName: !Ref ProjectName
        DomainName: !Ref DomainName
      Tags:
        - Key: 'chatanoo:project'
          Value: !Ref ProjectName
        - Key: 'chatanoo:component'
          Value: 'network'

  MediasCenter:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join ['', [!Ref DeploymentUrl, 'infra/mediascenter/1.0.2.cform']]
      Parameters:
        ProjectName: !Ref ProjectName
        CreateDNSRecord: false #true
        DomainName: !Ref DomainName
        SubDomainName: medias
        Route53HostedZone: !GetAtt Network.Outputs.HostedZone
        TranscoderSourceUrl: !Join ['', [!Ref DeploymentUrl, 'mediascenter/transcoder/1.0.1.zip']]
        S3UploadRepoBucket: !Ref Repo
        ElasticTranscoderPipelineLambda: !GetAtt LambdaCustomResources.Outputs.ElasticTranscoderPipeline
        ElasticTranscoderPresetLambda: !GetAtt LambdaCustomResources.Outputs.ElasticTranscoderPreset
        S3UploaderLambda: !GetAtt LambdaCustomResources.Outputs.S3Uploader
        CloudFrontIdentityLambda: !GetAtt LambdaCustomResources.Outputs.CloudFrontIdentity
        # CloudFrontCertificateLambda: !GetAtt LambdaCustomResources.Outputs.CloudFrontCertificate
        CognitoIdentityPoolLambda: !GetAtt LambdaCustomResources.Outputs.CognitoIdentityPool
        CognitoIdentityPoolRolesLambda: !GetAtt LambdaCustomResources.Outputs.CognitoIdentityPoolRoles
      Tags:
        - Key: 'chatanoo:project'
          Value: !Ref ProjectName
        - Key: 'chatanoo:component'
          Value: 'mediascenter'

  Mobile:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join ['', [!Ref DeploymentUrl, 'infra/mobile/1.0.1.cfn.yml']]
      Parameters:
        ProjectName: !Ref ProjectName
        CreateDNSRecord: false #true
        DomainName: !Ref DomainName
        SubDomainName: m
        Route53HostedZone: !GetAtt Network.Outputs.HostedZone
        DeploymentZipUrl: !Join ['', [!Ref DeploymentUrl, 'mobile/1.0.1.zip']]
        WSURL: !Join ['', ['https://core.', !Ref DomainName]] #!GetAtt Core.Outputs.Url
        MediaCenterUrl: !GetAtt MediasCenter.Outputs.CDNDistributionUrl #!GetAtt MediasCenter.Outputs.Url
        MediaCenterInputBucket: !GetAtt MediasCenter.Outputs.InputBucket
        MediaCenterIdentityPool: !GetAtt MediasCenter.Outputs.UploadIdentityPool
        S3UploaderLambda: !GetAtt LambdaCustomResources.Outputs.S3Uploader
        CloudFrontIdentityLambda: !GetAtt LambdaCustomResources.Outputs.CloudFrontIdentity
        # CloudFrontCertificateLambda: !GetAtt LambdaCustomResources.Outputs.CloudFrontCertificate
      Tags:
        - Key: 'chatanoo:project'
          Value: !Ref ProjectName
        - Key: 'chatanoo:component'
          Value: 'mobile'

  Admin:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join ['', [!Ref DeploymentUrl, 'infra/admin/1.0.5.cform']]
      Parameters:
        ProjectName: !Ref ProjectName
        CreateDNSRecord: false #true
        DomainName: !Ref DomainName
        SubDomainName: admin
        Route53HostedZone: !GetAtt Network.Outputs.HostedZone
        DeploymentZipUrl: !Join ['', [!Ref DeploymentUrl, 'admin/1.0.5.zip']]
        WSURL: !Join ['', ['https://core.', !Ref DomainName]] #!GetAtt Core.Outputs.Url
        MobileInterfaceUrl: !GetAtt Mobile.Outputs.CloudFrontUrl #!GetAtt Mobile.Outputs.Url
        MediaCenterUrl: !GetAtt MediasCenter.Outputs.CDNDistributionUrl #!GetAtt MediasCenter.Outputs.Url
        MediaCenterInputBucket: !GetAtt MediasCenter.Outputs.InputBucket
        MediaCenterIdentityPool: !GetAtt MediasCenter.Outputs.UploadIdentityPool
        S3UploaderLambda: !GetAtt LambdaCustomResources.Outputs.S3Uploader
        CloudFrontIdentityLambda: !GetAtt LambdaCustomResources.Outputs.CloudFrontIdentity
        # CloudFrontCertificateLambda: !GetAtt LambdaCustomResources.Outputs.CloudFrontCertificate
      Tags:
        - Key: 'chatanoo:project'
          Value: !Ref ProjectName
        - Key: 'chatanoo:component'
          Value: 'admin'

Outputs:
  MediasCenterUrl:
    Value: !Join ['', ['https://medias.', !Ref DomainName]] #!GetAtt MediasCenter.Outputs.Url
  AdminUrl:
    Value: !Join ['', ['https://admin.', !Ref DomainName]] #!GetAtt Admin.Outputs.Url
  MobileUrl:
    Value: !Join ['', ['https://m.', !Ref DomainName]] #!GetAtt Mobile.Outputs.Url
