AWSTemplateFormatVersion: 2010-09-09
Description: |
  Chatanoo Infrastructure

Metadata:

Parameters:
  DomainName:
    Type: String
  ProjectName:
    Type: String

  DeploymentUrl:
    Type: String
    Default: https://s3-eu-west-1.amazonaws.com/chatanoo-deployment/
  DeploymentBucket:
    Type: String
    Default: chatanoo-deployment

Mappings:

Conditions:

Resources:

  Repo:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "retain"
    Properties:
      Tags:
        - key: 'chatanoo:project'
          value: !Ref ProjectName

  LambdaCustomResources:
    Type: "AWS::CloudFormation::Stack"
    TemplateURL: !Join ['', [!Ref DeploymentUrl, 'infra/resources/1.0.0.cform']]
    Parameters:
      DeploymentBucket: !Ref DeploymentBucket
      CloudFrontIdentityKey: "aws-cloudformation-cloudfront-identity/1.0.1.zip"
      CognitoIdentityPoolKey: "aws-cloudformation-cognito-identitypool/1.0.0.zip"
      CognitoIdentityPoolRolesKey: "aws-cloudformation-cognito-identitypoolroles/1.0.0.zip"
      CognitoUserPoolKey: "aws-cloudformation-cognito-userpool/1.0.0.zip"
      CognitoUserPoolClientKey: "aws-cloudformation-cognito-userpoolclient/1.0.1.zip"
      CognitoUserPoolCustomAttributesKey: "aws-cloudformation-cognito-userpoolcustomattributes/1.0.1.zip"
      DynamoDBItemKey: "aws-cloudformation-dynamodb-item/1.0.0.zip"
      ElasticTranscoderPipelineKey: "aws-cloudformation-elastic-transcoder-pipeline/1.0.0.zip"
      ElasticTranscoderPresetKey: "aws-cloudformation-elastic-transcoder-preset/1.0.0.zip"
      S3UploaderKey: "aws-cloudformation-s3-uploader/1.0.0.zip"
      Tags:
        - key: 'chatanoo:project'
          value: !Ref ProjectName
        - key: 'chatanoo:component'
          value: 'resources'

  Network:
    Type: "AWS::CloudFormation::Stack"
    TemplateURL: !Join ['', [!Ref DeploymentUrl, 'infra/network/1.0.0.cfn.yml']]
    Parameters:
      ProjectName: !Ref ProjectName
      DomainName: !Ref DomainName
      Tags:
        - key: 'chatanoo:project'
          value: !Ref ProjectName
        - key: 'chatanoo:component'
          value: 'network'

  MediasCenter:
    Type: "AWS::CloudFormation::Stack"
    TemplateURL: !Join ['', [!Ref DeploymentUrl, 'infra/mediascenter/1.0.1.cform']]
    Parameters:
      ProjectName: !Ref ProjectName
      CreateDNSRecord: true
      DomainName: !Ref DomainName
      SubDomainName: medias
      Route53HostedZone: !GetAttr Network.HostedZone
      TranscoderSourceUrl: !Join ['', [!Ref DeploymentUrl, 'infra/mediascenter/1.0.0.cform']]
      S3UploadRepoBucket: !Ref Repo
      ElasticTranscoderPipelineLambda: !GetAttr LambdaCustomResources.ElasticTranscoderPipeline
      ElasticTranscoderPresetLambda: !GetAttr LambdaCustomResources.ElasticTranscoderPreset
      S3UploaderLambda: !GetAttr LambdaCustomResources.S3Uploader
      CloudFrontIdentityLambda: !GetAttr LambdaCustomResources.CloudFrontIdentity
      CloudFrontCertificateLambda: !GetAttr LambdaCustomResources.CloudFrontCertificate
      CognitoIdentityPoolLambda: !GetAttr LambdaCustomResources.CognitoIdentityPool
      CognitoIdentityPoolRolesLambda: !GetAttr LambdaCustomResources.CognitoIdentityPoolRoles
      Tags:
        - key: 'chatanoo:project'
          value: !Ref ProjectName
        - key: 'chatanoo:component'
          value: 'mediascenter'

  Admin:
    Type: "AWS::CloudFormation::Stack"
    TemplateURL: !Join ['', [!Ref DeploymentUrl, 'infra/admin/1.0.0.cform']]
    Parameters:
      ProjectName: !Ref ProjectName
      CreateDNSRecord: true
      DomainName: !Ref DomainName
      SubDomainName: admin
      Route53HostedZone: !GetAttr Network.HostedZone
      DeploymentZipUrl: !Join ['', [!Ref DeploymentUrl, 'admin/1.0.2.zip']]
      WSURL: "" #!GetAttr Core.Url
      MobileInterfaceUrl: "" #!GetAttr Mobile.Url
      MediaCenterUrl: !GetAttr MediasCenter.Url
      MediaCenterInputBucket: !GetAttr MediasCenter.InputBucket
      MediaCenterIdentityPool: !GetAttr MediasCenter.UploadIdentityPool
      S3UploaderLambda: !GetAttr LambdaCustomResources.S3Uploader
      CloudFrontIdentityLambda: !GetAttr LambdaCustomResources.CloudFrontIdentity
      CloudFrontCertificateLambda: !GetAttr LambdaCustomResources.CloudFrontCertificate
      Tags:
        - key: 'chatanoo:project'
          value: !Ref ProjectName
        - key: 'chatanoo:component'
          value: 'admin'



Outputs:
  MediasCenterUrl:
    Value: !GetAttr MediasCenter.Url
  AdminUrl:
    Value: !GetAttr Admin.Url
