AWSTemplateFormatVersion: 2010-09-09
Description: |
  Chatanoo Network

# Metadata:

Parameters:
  DomainName:
    Type: String
  ProjectName:
    Type: String

# Mappings:

# Conditions:

Resources:

  PublicDNS:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join ['', ['[Chatanoo] Public Hosted zone for', !Ref ProjectName]]
      Name: !Ref DomainName
      HostedZoneTags:
        - Key: 'chatanoo:project'
          Value: !Ref ProjectName
        - Key: 'chatanoo:component'
          Value: 'network'

Outputs:
  HostedZone:
    Description: Id of the Hosted Zone created
    Value: !Ref PublicDNS
